# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#

name: Java CI with Maven

on:
  push:
    branches: [ main,develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main,develop ]
    paths-ignore:
      - README.md
      - .gitignore

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Cache Maven Repos
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Plugin
        run: mvn -B clean package install --file pom.xml
      - uses: bhowell2/github-substring-action@v1.0.0
        if: startsWith(github.ref, 'refs/tags/')
        id: releaseVersion
        with:
          fail_if_not_found: false
          default_return_value: ${{ github.ref }}
          value: ${{ github.ref }}
          index_of_str: "refs/tags/v"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: ./fizz-header-request-plugin-${{ steps.releaseVersion.outputs.substring }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Apache Maven Central
        if: startsWith(github.ref, 'refs/tags/')
        uses: samuelmeuli/action-maven-publish@v1
        with:
          maven_profiles: release
          server_id: sonatype-release
          gpg_private_key: ${{ secrets.GPG_SECRET }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHASE }}
          nexus_username: ${{ secrets.OSSRH_USER }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
